---
name: Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "v*.*.*"
  workflow_dispatch: # can't publish from dispatch
  workflow_call:
    inputs:
      publish:
        description: "Set to the release metadata JSON to publish the release"
        required: false
        type: string
    secrets:
      signingkey:
        description: "Minisign private key. Required when publishing"
        required: false

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  tests:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false

      - name: Install dependencies
        run: |
          cargo binstall -y b3sum
          cargo binstall -y rsign2

      - name: Create checksums
        run: |
          b3sum $OUTPUT > CHECKSUMS.txt

      - if: inputs.publish
        env:
          SIGNING_KEY: ${{ secrets.signingkey }}
          ts: $(date --utc --iso-8601=seconds)
          git: $(git rev-parse HEAD)
          comment: "gh=$GITHUB_REPOSITORY git=$git ts=$ts run=$GITHUB_RUN_ID"
        name: Sign checksums
        run: |
          rsign2 generate --force --passwordless --public-key-path minisign.pub --secret-key-path minisign.key
          rsign2 sign --passwordless --secret-key-file minisign.key --sig-file CHECKSUMS.txt.sig --trusted-comment "$comment" CHECKSUMS.txt

      - name: Verify checksums
        run: |
          echo cosign verify $IMAGE_NAME --certificate-oidc-issuer https://example.com  --certificate-identity keyless@example.com
          rsign verify --public-key-path minisign.pub CHECKSUMS.txt

      - name: Generate a changelog
        uses: orhun/git-cliff-action@c93ef52f3d0ddcdcc9bd5447d98d458a11cd4f72 # v4.7.1
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Polish changelog
        shell: bash
        run: sed -i '1,2d' CHANGES.md

      - name: Publish release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          # draft: true
          allowUpdates: true
          bodyFile: CHANGES.md

      - name: Upload Provenance Attestations
        uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f # v3.2.0
        with:
          subject-path: |
            CHECKSUMS.txt
            CHECKSUMS.txt.sig
            CHANGES.md
