---
name: Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - v*

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  tests:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create checksums
        run:
          - b3sum $OUTPUT > CHECKSUMS.txt

      - name: Sign checksums
        run:
          - rsign2 generate --passwordless
          - rsign2 sign $CHECKSUMS.txt -t "Release $tag"

      - name: Verify checksums
        run:
          - echo cosign verify $IMAGE_NAME --certificate-oidc-issuer https://example.com  --certificate-identity keyless@example.com
          - echo rsign verify CHECKSUMS.txt -p rsign.pub

      - name: Publish release
        run: echo publish release...
