name: Security Scan

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # For checking out the repo
      security-events: write # For uploading results to the Security tab

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          scan-type: "fs" # Scan the filesystem (repo)
          scan-ref: "." # Scan the current directory
          format: "sarif" # Use SARIF format for GitHub Code Scanning
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@cf1bb45a277cb3c205638b2cd5c984db1c46a412 # v4.31.7
        with:
          sarif_file: "trivy-results.sarif"

  trufflehog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Fetch all history to ensure a complete scan
          fetch-depth: 0
          persist-credentials: false

      - name: Run TruffleHog OSS
        # Use the official TruffleHog action
        uses: trufflesecurity/trufflehog@ef6e76c3c4023279497fab4721ffa071a722fd05 # v3.92.4
        with:
          # Scan only for verified secrets (fewer false positives)
          extra_args: --results=verified,unknown
