---
name: Tests

on: # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build
        uses: yonasBSD/toolkit@e3156a095eb4a759778ad8ef10dfd58dd00993e6 # v0.1.0
        with:
          run: |
            task build

      - name: Run tests
        uses: yonasBSD/toolkit@e3156a095eb4a759778ad8ef10dfd58dd00993e6 # v0.1.0
        with:
          run: |
            task test
