name: Todo List

on:
  workflow_dispatch:

jobs:
  todo-list:
    name: Remaining Todos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: nightly

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@80aaafe04903087c333980fa2686259ddd34b2d9 # main

      - name: Install Cocogitto
        run: cargo binstall -y todo-tree

      - name: List Todos
        run: |
          SUMMARY_FILE=$GITHUB_STEP_SUMMARY
          TODO_OUTPUT=$(todo-tree list)

          # Check if output is empty and provide a clear success message if so.
          if [ -z "$TODO_OUTPUT" ]; then
            echo "## 🌳 TODO-Tree Code Review Report" >> $SUMMARY_FILE
            echo "" >> $SUMMARY_FILE
            echo "✅ **Success**" >> $SUMMARY_FILE
            exit 0
          fi

          # --- END: Execute todo-tree command ---

          # 1. Add a descriptive Markdown header to the Summary page
          echo "## 🌳 TODO-Tree Code Review Report" >> $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE

          # 2. Append the raw output directly (preserves ANSI colors)
          todo-tree list --case-sensitive >> $SUMMARY_FILE
          todo-tree stats >> $SUMMARY_FILE
